#settings intended for single subject analysis
#data scaling (for now only option allowed is "psc" or equivalently "percent_signal_change".
data_scaling: "zsc"

crossvalidate: True
#always specify only one of these two
#fit_task: "2R"
fit_runs: [1,3,5]
save_noise_ceiling: False
return_noise_ceiling_fraction: False
save_runs: []
save_raw_timecourse: False

#if fitting the hrf, set single_hrf to True to use median hrf when crossvalidating. also applies when iterating
#however, if  hrf is not being fit at all, set this to False
single_hrf: False

norm_model_variant: "abcd"

#how to handle existing outputs (overwrite, iterate, skip)
refit_mode: "skip"

#expected max duration in hours:minutes
duration: "4:55"

#data chunks (50 good number for V1V2V3, 500 whole brain)
n_chunks: 100
#choices: fsnative, fsaverage (surface fitting), T1w (volume fitting)      
fitting_space: "fsnative"
data_path: "/scratch-shared/marcoaq/PRFMapping/PRFMapping-Deriv-hires"
#path to file with ROI indices
#roi_idx_path: "/home/marcoaq/$subj$_OccPole.npy"

#fitting tolerance
xtol: 0.00001
ftol: 0.00001
#grid fit will only allow positive prfs
pos_prfs_only: True

#perform bounded iterative fit? (L-BFGS-B if True, powell if False) (all models)
param_bounds: True

#set bold baseline to 100 for all models, norm to value below
fix_bold_baseline: True
norm_bold_baseline: 0

#constraints on surround models (positive center, large surround) (trust-constr minimizer)
param_constraints: True
positive_centre_only: False
surround_sigma_larger_than_centre: False

#unit volume RFs
normalize_RFs: False

#whether to fit hrf or not
fit_hrf: False
#explicit hrf or spm hrf params. see prfpy for details
hrf: [1,4.6,0]

#DM size in pixels (n_pix x n_pix) (has to be divisor of 1080)
n_pix: 54 #54 #40,108
#pixels to be set to zero in matrix (top, bottom, left, right)
dm_edges_clipping: [6,1,0,1]
#normalize prf*stim*dx**2 as an integral
normalize_integral_dx: False

#screen settings
screen_size_cm: 39.3
screen_distance_cm: 210
#data settings
TR: 1.5

#volumes to remove at beginning of time series
discard_volumes: 4
#volumes used in beginning/end to calculate the baseline
baseline_volumes_begin_end: [10,5]
#discard time series with too low variance (max deviation from mean < min_percent_var % of mean)
min_percent_var: 0.25

#filter types: "sg" for savitzky golay or "dc" for discrete cosines
filter_predictions: False
filter_type: "dc"

#params for discrete cosine filtering
first_modes_to_remove: 5
last_modes_to_remove_percent: 0

#params for savgol filtering (window can be a number or 'adaptive')
window_length: 'adaptive' 
polyorder: 1
highpass: True
add_mean: True

#rsq threshold for iterative fit
rsq_threshold: 0.05

#standard Cartesius parallelization
n_jobs: 23
#mkl_num_threads: 4
#number of voxel batches (for grid fits)
n_batches: 23

#models to fit (gauss, CSS, DoG, norm):
models_to_fit:
           - "gauss"
           - "DoG"
           - "CSS"
           - "norm"   

dog_grid: False
css_grid: False        

task_names:
           - "1R"
           - "1S"
           - "2R"
           - "4F"
           - "4R"

screenshot_paths:
                  - "/scratch-shared/marcoaq/PRFMapping/sub-001_ses-1_Logs/sub-001_ses-1_task-1R_run-1_Logs/Screenshots"
                  - "/scratch-shared/marcoaq/PRFMapping/sub-001_ses-1_Logs/sub-001_ses-1_task-1S_run-1_Logs/Screenshots"
                  - "/scratch-shared/marcoaq/PRFMapping/sub-001_ses-1_Logs/sub-001_ses-1_task-2R_run-1_Logs/Screenshots"
                  - "/scratch-shared/marcoaq/PRFMapping/sub-001_ses-1_Logs/sub-001_ses-1_task-4F_run-1_Logs/Screenshots"
                  - "/scratch-shared/marcoaq/PRFMapping/sub-001_ses-1_Logs/sub-001_ses-1_task-4R_run-1_Logs/Screenshots"


verbose: False


#if timecourse was already preprocessed, specify
#timecourse_data_path: "/home/marcoaq/PRFMapping/PRFMapping-Deriv-hires/sub-006_timecourse_space-fsnative-part2.npy"

#if gaussian grid data was already obtained, can specify path
#grid_data_path: "/home/marcoaq/PRFMapping/PRFMapping-Deriv-hires/prfpy/sub-006_gridparams-gauss_space-fsnative2020-02-05-17-27-16.npy"
#gauss iterparams (or specific model start params)
#gauss_iterparams_path: "/home/marcoaq/PRFMapping/PRFMapping-Deriv-hires/sub-006_iterparams-gauss_space-fsnative2020-02-05-17-27-16.npy"
#css iterparams (or specific model start params)
#css_iterparams_path: "/home/marcoaq/PRFMapping/PRFMapping-Deriv-hires/sub-006_iterparams-css_space-fsnative2020-02-05-17-27-16.npy"
#dog iterparams (or specific model start params)
#dog_iterparams_path: "/home/marcoaq/PRFMapping/PRFMapping-Deriv-hires/sub-006_iterparams-dog_space-fsnative2020-02-05-17-27-16.npy"
#norm gridparams path
#norm_gridparams_path: "/home/marcoaq/PRFMapping/PRFMapping-Deriv-hires/sub-006_gridparams-norm_space-fsnative2020-02-05-17-27-16.npy"
#norm iter params path
#norm_iterparams_path: "/home/marcoaq/PRFMapping/PRFMapping-Deriv-hires/sub-006_iterparams-norm_space-fsnative2020-02-05-17-27-16.npy"
